version: '3.8'

services:
  db:
    image: mysql
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_PORT_LOCAL:$MYSQLDB_PORT_DOCKER
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - $NODE_PORT_LOCAL:$NODE_PORT_DOCKER
    